// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220110.5

#pragma once
#ifndef WINRT_Microsoft_UI_UIAutomation_1_H
#define WINRT_Microsoft_UI_UIAutomation_1_H
#include "winrt/impl/Microsoft.UI.UIAutomation.0.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::UIAutomation
{
    struct __declspec(empty_bases) IAutomationRemoteActiveEnd :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteActiveEnd>
    {
        IAutomationRemoteActiveEnd(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteActiveEnd(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteAnimationStyle :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteAnimationStyle>
    {
        IAutomationRemoteAnimationStyle(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteAnimationStyle(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteAnnotationPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteAnnotationPattern>
    {
        IAutomationRemoteAnnotationPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteAnnotationPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteAnnotationType :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteAnnotationType>
    {
        IAutomationRemoteAnnotationType(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteAnnotationType(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteAnyObject :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteAnyObject>
    {
        IAutomationRemoteAnyObject(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteAnyObject(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteArray :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteArray>
    {
        IAutomationRemoteArray(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteArray(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteBool :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteBool>
    {
        IAutomationRemoteBool(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteBool(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteBulletStyle :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteBulletStyle>
    {
        IAutomationRemoteBulletStyle(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteBulletStyle(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteByteArray :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteByteArray>
    {
        IAutomationRemoteByteArray(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteByteArray(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteCacheRequest :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteCacheRequest>
    {
        IAutomationRemoteCacheRequest(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteCacheRequest(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteCapStyle :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteCapStyle>
    {
        IAutomationRemoteCapStyle(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteCapStyle(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteCaretBidiMode :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteCaretBidiMode>
    {
        IAutomationRemoteCaretBidiMode(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteCaretBidiMode(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteCaretPosition :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteCaretPosition>
    {
        IAutomationRemoteCaretPosition(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteCaretPosition(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteChar :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteChar>
    {
        IAutomationRemoteChar(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteChar(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteConnectionBoundObject :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteConnectionBoundObject>
    {
        IAutomationRemoteConnectionBoundObject(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteConnectionBoundObject(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteControlType :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteControlType>
    {
        IAutomationRemoteControlType(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteControlType(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteCustomNavigationPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteCustomNavigationPattern>
    {
        IAutomationRemoteCustomNavigationPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteCustomNavigationPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteDockPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteDockPattern>
    {
        IAutomationRemoteDockPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteDockPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteDockPosition :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteDockPosition>
    {
        IAutomationRemoteDockPosition(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteDockPosition(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteDouble :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteDouble>
    {
        IAutomationRemoteDouble(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteDouble(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteDragPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteDragPattern>
    {
        IAutomationRemoteDragPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteDragPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteDropTargetPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteDropTargetPattern>
    {
        IAutomationRemoteDropTargetPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteDropTargetPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteElement :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteElement>
    {
        IAutomationRemoteElement(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteElement(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteExpandCollapsePattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteExpandCollapsePattern>
    {
        IAutomationRemoteExpandCollapsePattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteExpandCollapsePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteExpandCollapseState :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteExpandCollapseState>
    {
        IAutomationRemoteExpandCollapseState(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteExpandCollapseState(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteExtensionTarget :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteExtensionTarget>
    {
        IAutomationRemoteExtensionTarget(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteExtensionTarget(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteExtensionTargetFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteExtensionTargetFactory>
    {
        IAutomationRemoteExtensionTargetFactory(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteExtensionTargetFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteFlowDirections :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteFlowDirections>
    {
        IAutomationRemoteFlowDirections(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteFlowDirections(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteGridItemPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteGridItemPattern>
    {
        IAutomationRemoteGridItemPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteGridItemPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteGridPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteGridPattern>
    {
        IAutomationRemoteGridPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteGridPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteGuid :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteGuid>
    {
        IAutomationRemoteGuid(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteGuid(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteHeadingLevel :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteHeadingLevel>
    {
        IAutomationRemoteHeadingLevel(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteHeadingLevel(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteHorizontalTextAlignment :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteHorizontalTextAlignment>
    {
        IAutomationRemoteHorizontalTextAlignment(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteHorizontalTextAlignment(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteInt :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteInt>
    {
        IAutomationRemoteInt(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteInt(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteInvokePattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteInvokePattern>
    {
        IAutomationRemoteInvokePattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteInvokePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteItemContainerPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteItemContainerPattern>
    {
        IAutomationRemoteItemContainerPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteItemContainerPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteLandmarkType :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteLandmarkType>
    {
        IAutomationRemoteLandmarkType(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteLandmarkType(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteLegacyIAccessiblePattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteLegacyIAccessiblePattern>
    {
        IAutomationRemoteLegacyIAccessiblePattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteLegacyIAccessiblePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteLiveSetting :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteLiveSetting>
    {
        IAutomationRemoteLiveSetting(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteLiveSetting(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteMetadata :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteMetadata>
    {
        IAutomationRemoteMetadata(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteMetadata(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteMultipleViewPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteMultipleViewPattern>
    {
        IAutomationRemoteMultipleViewPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteMultipleViewPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteNavigateDirection :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteNavigateDirection>
    {
        IAutomationRemoteNavigateDirection(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteNavigateDirection(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteObject :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteObject>
    {
        IAutomationRemoteObject(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteObject(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteObjectFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteObjectFactory>
    {
        IAutomationRemoteObjectFactory(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteObjectFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteOperation :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteOperation>
    {
        IAutomationRemoteOperation(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteOperation(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteOperationResultSet :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteOperationResultSet>
    {
        IAutomationRemoteOperationResultSet(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteOperationResultSet(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteOrientationType :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteOrientationType>
    {
        IAutomationRemoteOrientationType(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteOrientationType(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteOutlineStyles :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteOutlineStyles>
    {
        IAutomationRemoteOutlineStyles(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteOutlineStyles(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemotePatternId :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemotePatternId>
    {
        IAutomationRemotePatternId(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemotePatternId(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemotePoint :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemotePoint>
    {
        IAutomationRemotePoint(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemotePoint(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemotePropertyId :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemotePropertyId>
    {
        IAutomationRemotePropertyId(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemotePropertyId(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteRangeValuePattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteRangeValuePattern>
    {
        IAutomationRemoteRangeValuePattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteRangeValuePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteRect :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteRect>
    {
        IAutomationRemoteRect(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteRect(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteRowOrColumnMajor :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteRowOrColumnMajor>
    {
        IAutomationRemoteRowOrColumnMajor(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteRowOrColumnMajor(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteSayAsInterpretAs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteSayAsInterpretAs>
    {
        IAutomationRemoteSayAsInterpretAs(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteSayAsInterpretAs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteScrollAmount :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteScrollAmount>
    {
        IAutomationRemoteScrollAmount(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteScrollAmount(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteScrollItemPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteScrollItemPattern>
    {
        IAutomationRemoteScrollItemPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteScrollItemPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteScrollPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteScrollPattern>
    {
        IAutomationRemoteScrollPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteScrollPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteSelectionItemPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteSelectionItemPattern>
    {
        IAutomationRemoteSelectionItemPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteSelectionItemPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteSelectionPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteSelectionPattern>
    {
        IAutomationRemoteSelectionPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteSelectionPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteSelectionPattern2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteSelectionPattern2>
    {
        IAutomationRemoteSelectionPattern2(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteSelectionPattern2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteSpreadsheetItemPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteSpreadsheetItemPattern>
    {
        IAutomationRemoteSpreadsheetItemPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteSpreadsheetItemPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteSpreadsheetPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteSpreadsheetPattern>
    {
        IAutomationRemoteSpreadsheetPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteSpreadsheetPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteString :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteString>
    {
        IAutomationRemoteString(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteString(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteStringMap :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteStringMap>
    {
        IAutomationRemoteStringMap(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteStringMap(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteStyleId :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteStyleId>
    {
        IAutomationRemoteStyleId(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteStyleId(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteStylesPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteStylesPattern>
    {
        IAutomationRemoteStylesPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteStylesPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteSupportedTextSelection :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteSupportedTextSelection>
    {
        IAutomationRemoteSupportedTextSelection(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteSupportedTextSelection(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteSynchronizedInputPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteSynchronizedInputPattern>
    {
        IAutomationRemoteSynchronizedInputPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteSynchronizedInputPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteSynchronizedInputType :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteSynchronizedInputType>
    {
        IAutomationRemoteSynchronizedInputType(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteSynchronizedInputType(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTableItemPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTableItemPattern>
    {
        IAutomationRemoteTableItemPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTableItemPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTablePattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTablePattern>
    {
        IAutomationRemoteTablePattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTablePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTextAttributeId :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTextAttributeId>
    {
        IAutomationRemoteTextAttributeId(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTextAttributeId(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTextChildPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTextChildPattern>
    {
        IAutomationRemoteTextChildPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTextChildPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTextDecorationLineStyle :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTextDecorationLineStyle>
    {
        IAutomationRemoteTextDecorationLineStyle(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTextDecorationLineStyle(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTextEditPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTextEditPattern>
    {
        IAutomationRemoteTextEditPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTextEditPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTextPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTextPattern>
    {
        IAutomationRemoteTextPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTextPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTextPattern2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTextPattern2>
    {
        IAutomationRemoteTextPattern2(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTextPattern2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTextPatternRangeEndpoint :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTextPatternRangeEndpoint>
    {
        IAutomationRemoteTextPatternRangeEndpoint(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTextPatternRangeEndpoint(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTextRange :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTextRange>
    {
        IAutomationRemoteTextRange(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTextRange(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTextUnit :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTextUnit>
    {
        IAutomationRemoteTextUnit(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTextUnit(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTogglePattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTogglePattern>
    {
        IAutomationRemoteTogglePattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTogglePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteToggleState :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteToggleState>
    {
        IAutomationRemoteToggleState(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteToggleState(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTransformPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTransformPattern>
    {
        IAutomationRemoteTransformPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTransformPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteTransformPattern2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteTransformPattern2>
    {
        IAutomationRemoteTransformPattern2(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteTransformPattern2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteUint :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteUint>
    {
        IAutomationRemoteUint(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteUint(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteValuePattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteValuePattern>
    {
        IAutomationRemoteValuePattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteValuePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteVirtualizedItemPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteVirtualizedItemPattern>
    {
        IAutomationRemoteVirtualizedItemPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteVirtualizedItemPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteWindowInteractionState :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteWindowInteractionState>
    {
        IAutomationRemoteWindowInteractionState(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteWindowInteractionState(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteWindowPattern :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteWindowPattern>
    {
        IAutomationRemoteWindowPattern(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteWindowPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteWindowVisualState :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteWindowVisualState>
    {
        IAutomationRemoteWindowVisualState(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteWindowVisualState(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutomationRemoteZoomUnit :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteZoomUnit>
    {
        IAutomationRemoteZoomUnit(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteZoomUnit(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
