// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220110.5

#pragma once
#ifndef WINRT_Microsoft_UI_UIAutomation_2_H
#define WINRT_Microsoft_UI_UIAutomation_2_H
#include "winrt/impl/Microsoft.UI.UIAutomation.1.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::UIAutomation
{
    struct AutomationRemoteOperationScopeHandler : winrt::Windows::Foundation::IUnknown
    {
        AutomationRemoteOperationScopeHandler(std::nullptr_t = nullptr) noexcept {}
        AutomationRemoteOperationScopeHandler(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IUnknown(ptr, take_ownership_from_abi) {}
        template <typename L> AutomationRemoteOperationScopeHandler(L lambda);
        template <typename F> AutomationRemoteOperationScopeHandler(F* function);
        template <typename O, typename M> AutomationRemoteOperationScopeHandler(O* object, M method);
        template <typename O, typename M> AutomationRemoteOperationScopeHandler(com_ptr<O>&& object, M method);
        template <typename O, typename M> AutomationRemoteOperationScopeHandler(weak_ref<O>&& object, M method);
        auto operator()() const;
    };
    struct AutomationRemoteOperationResponseToken
    {
        int32_t Value;
    };
    inline bool operator==(AutomationRemoteOperationResponseToken const& left, AutomationRemoteOperationResponseToken const& right) noexcept
    {
        return left.Value == right.Value;
    }
    inline bool operator!=(AutomationRemoteOperationResponseToken const& left, AutomationRemoteOperationResponseToken const& right) noexcept
    {
        return !(left == right);
    }
    struct __declspec(empty_bases) AutomationRemoteActiveEnd : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteActiveEnd,
        impl::base<AutomationRemoteActiveEnd, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteActiveEnd, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteActiveEnd(std::nullptr_t) noexcept {}
        AutomationRemoteActiveEnd(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteActiveEnd(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteAnimationStyle : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteAnimationStyle,
        impl::base<AutomationRemoteAnimationStyle, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteAnimationStyle, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteAnimationStyle(std::nullptr_t) noexcept {}
        AutomationRemoteAnimationStyle(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteAnimationStyle(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteAnnotationPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteAnnotationPattern,
        impl::base<AutomationRemoteAnnotationPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteAnnotationPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteAnnotationPattern(std::nullptr_t) noexcept {}
        AutomationRemoteAnnotationPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteAnnotationPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteAnnotationType : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteAnnotationType,
        impl::base<AutomationRemoteAnnotationType, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteAnnotationType, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteAnnotationType(std::nullptr_t) noexcept {}
        AutomationRemoteAnnotationType(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteAnnotationType(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteAnyObject : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteAnyObject,
        impl::base<AutomationRemoteAnyObject, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteAnyObject, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteAnyObject(std::nullptr_t) noexcept {}
        AutomationRemoteAnyObject(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteAnyObject(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteArray : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteArray,
        impl::base<AutomationRemoteArray, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteArray, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteArray(std::nullptr_t) noexcept {}
        AutomationRemoteArray(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteArray(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteBool : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteBool,
        impl::base<AutomationRemoteBool, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteBool, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteBool(std::nullptr_t) noexcept {}
        AutomationRemoteBool(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteBool(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteBulletStyle : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteBulletStyle,
        impl::base<AutomationRemoteBulletStyle, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteBulletStyle, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteBulletStyle(std::nullptr_t) noexcept {}
        AutomationRemoteBulletStyle(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteBulletStyle(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteByteArray : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteByteArray,
        impl::base<AutomationRemoteByteArray, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteByteArray, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteByteArray(std::nullptr_t) noexcept {}
        AutomationRemoteByteArray(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteByteArray(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteCacheRequest : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteCacheRequest,
        impl::base<AutomationRemoteCacheRequest, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteCacheRequest, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteCacheRequest(std::nullptr_t) noexcept {}
        AutomationRemoteCacheRequest(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteCacheRequest(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteCapStyle : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteCapStyle,
        impl::base<AutomationRemoteCapStyle, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteCapStyle, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteCapStyle(std::nullptr_t) noexcept {}
        AutomationRemoteCapStyle(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteCapStyle(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteCaretBidiMode : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteCaretBidiMode,
        impl::base<AutomationRemoteCaretBidiMode, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteCaretBidiMode, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteCaretBidiMode(std::nullptr_t) noexcept {}
        AutomationRemoteCaretBidiMode(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteCaretBidiMode(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteCaretPosition : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteCaretPosition,
        impl::base<AutomationRemoteCaretPosition, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteCaretPosition, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteCaretPosition(std::nullptr_t) noexcept {}
        AutomationRemoteCaretPosition(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteCaretPosition(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteChar : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteChar,
        impl::base<AutomationRemoteChar, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteChar, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteChar(std::nullptr_t) noexcept {}
        AutomationRemoteChar(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteChar(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteConnectionBoundObject : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteConnectionBoundObject,
        impl::base<AutomationRemoteConnectionBoundObject, winrt::Microsoft::UI::UIAutomation::AutomationRemoteExtensionTarget, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteConnectionBoundObject, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteExtensionTarget, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteConnectionBoundObject(std::nullptr_t) noexcept {}
        AutomationRemoteConnectionBoundObject(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteConnectionBoundObject(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteControlType : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteControlType,
        impl::base<AutomationRemoteControlType, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteControlType, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteControlType(std::nullptr_t) noexcept {}
        AutomationRemoteControlType(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteControlType(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteCustomNavigationPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteCustomNavigationPattern,
        impl::base<AutomationRemoteCustomNavigationPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteCustomNavigationPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteCustomNavigationPattern(std::nullptr_t) noexcept {}
        AutomationRemoteCustomNavigationPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteCustomNavigationPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteDockPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteDockPattern,
        impl::base<AutomationRemoteDockPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteDockPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteDockPattern(std::nullptr_t) noexcept {}
        AutomationRemoteDockPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteDockPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteDockPosition : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteDockPosition,
        impl::base<AutomationRemoteDockPosition, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteDockPosition, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteDockPosition(std::nullptr_t) noexcept {}
        AutomationRemoteDockPosition(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteDockPosition(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteDouble : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteDouble,
        impl::base<AutomationRemoteDouble, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteDouble, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteDouble(std::nullptr_t) noexcept {}
        AutomationRemoteDouble(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteDouble(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteDragPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteDragPattern,
        impl::base<AutomationRemoteDragPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteDragPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteDragPattern(std::nullptr_t) noexcept {}
        AutomationRemoteDragPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteDragPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteDropTargetPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteDropTargetPattern,
        impl::base<AutomationRemoteDropTargetPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteDropTargetPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteDropTargetPattern(std::nullptr_t) noexcept {}
        AutomationRemoteDropTargetPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteDropTargetPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteElement : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteElement,
        impl::base<AutomationRemoteElement, winrt::Microsoft::UI::UIAutomation::AutomationRemoteExtensionTarget, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteElement, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteExtensionTarget, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteElement(std::nullptr_t) noexcept {}
        AutomationRemoteElement(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteElement(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteExpandCollapsePattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteExpandCollapsePattern,
        impl::base<AutomationRemoteExpandCollapsePattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteExpandCollapsePattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteExpandCollapsePattern(std::nullptr_t) noexcept {}
        AutomationRemoteExpandCollapsePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteExpandCollapsePattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteExpandCollapseState : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteExpandCollapseState,
        impl::base<AutomationRemoteExpandCollapseState, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteExpandCollapseState, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteExpandCollapseState(std::nullptr_t) noexcept {}
        AutomationRemoteExpandCollapseState(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteExpandCollapseState(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteExtensionTarget : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteExtensionTarget,
        impl::base<AutomationRemoteExtensionTarget, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteExtensionTarget, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteExtensionTarget(std::nullptr_t) noexcept {}
        AutomationRemoteExtensionTarget(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteExtensionTarget(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteFlowDirections : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteFlowDirections,
        impl::base<AutomationRemoteFlowDirections, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteFlowDirections, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteFlowDirections(std::nullptr_t) noexcept {}
        AutomationRemoteFlowDirections(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteFlowDirections(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteGridItemPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteGridItemPattern,
        impl::base<AutomationRemoteGridItemPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteGridItemPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteGridItemPattern(std::nullptr_t) noexcept {}
        AutomationRemoteGridItemPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteGridItemPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteGridPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteGridPattern,
        impl::base<AutomationRemoteGridPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteGridPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteGridPattern(std::nullptr_t) noexcept {}
        AutomationRemoteGridPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteGridPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteGuid : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteGuid,
        impl::base<AutomationRemoteGuid, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteGuid, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteGuid(std::nullptr_t) noexcept {}
        AutomationRemoteGuid(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteGuid(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteHeadingLevel : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteHeadingLevel,
        impl::base<AutomationRemoteHeadingLevel, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteHeadingLevel, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteHeadingLevel(std::nullptr_t) noexcept {}
        AutomationRemoteHeadingLevel(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteHeadingLevel(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteHorizontalTextAlignment : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteHorizontalTextAlignment,
        impl::base<AutomationRemoteHorizontalTextAlignment, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteHorizontalTextAlignment, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteHorizontalTextAlignment(std::nullptr_t) noexcept {}
        AutomationRemoteHorizontalTextAlignment(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteHorizontalTextAlignment(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteInt : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteInt,
        impl::base<AutomationRemoteInt, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteInt, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteInt(std::nullptr_t) noexcept {}
        AutomationRemoteInt(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteInt(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteInvokePattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteInvokePattern,
        impl::base<AutomationRemoteInvokePattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteInvokePattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteInvokePattern(std::nullptr_t) noexcept {}
        AutomationRemoteInvokePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteInvokePattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteItemContainerPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteItemContainerPattern,
        impl::base<AutomationRemoteItemContainerPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteItemContainerPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteItemContainerPattern(std::nullptr_t) noexcept {}
        AutomationRemoteItemContainerPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteItemContainerPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteLandmarkType : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteLandmarkType,
        impl::base<AutomationRemoteLandmarkType, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteLandmarkType, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteLandmarkType(std::nullptr_t) noexcept {}
        AutomationRemoteLandmarkType(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteLandmarkType(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteLegacyIAccessiblePattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteLegacyIAccessiblePattern,
        impl::base<AutomationRemoteLegacyIAccessiblePattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteLegacyIAccessiblePattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteLegacyIAccessiblePattern(std::nullptr_t) noexcept {}
        AutomationRemoteLegacyIAccessiblePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteLegacyIAccessiblePattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteLiveSetting : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteLiveSetting,
        impl::base<AutomationRemoteLiveSetting, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteLiveSetting, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteLiveSetting(std::nullptr_t) noexcept {}
        AutomationRemoteLiveSetting(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteLiveSetting(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteMetadata : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteMetadata,
        impl::base<AutomationRemoteMetadata, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteMetadata, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteMetadata(std::nullptr_t) noexcept {}
        AutomationRemoteMetadata(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteMetadata(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteMultipleViewPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteMultipleViewPattern,
        impl::base<AutomationRemoteMultipleViewPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteMultipleViewPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteMultipleViewPattern(std::nullptr_t) noexcept {}
        AutomationRemoteMultipleViewPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteMultipleViewPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteNavigateDirection : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteNavigateDirection,
        impl::base<AutomationRemoteNavigateDirection, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteNavigateDirection, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteNavigateDirection(std::nullptr_t) noexcept {}
        AutomationRemoteNavigateDirection(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteNavigateDirection(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteObject : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject
    {
        AutomationRemoteObject(std::nullptr_t) noexcept {}
        AutomationRemoteObject(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteOperation : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteOperation
    {
        AutomationRemoteOperation(std::nullptr_t) noexcept {}
        AutomationRemoteOperation(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteOperation(ptr, take_ownership_from_abi) {}
        AutomationRemoteOperation();
    };
    struct __declspec(empty_bases) AutomationRemoteOperationResultSet : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteOperationResultSet
    {
        AutomationRemoteOperationResultSet(std::nullptr_t) noexcept {}
        AutomationRemoteOperationResultSet(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteOperationResultSet(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteOrientationType : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteOrientationType,
        impl::base<AutomationRemoteOrientationType, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteOrientationType, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteOrientationType(std::nullptr_t) noexcept {}
        AutomationRemoteOrientationType(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteOrientationType(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteOutlineStyles : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteOutlineStyles,
        impl::base<AutomationRemoteOutlineStyles, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteOutlineStyles, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteOutlineStyles(std::nullptr_t) noexcept {}
        AutomationRemoteOutlineStyles(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteOutlineStyles(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemotePatternId : winrt::Microsoft::UI::UIAutomation::IAutomationRemotePatternId,
        impl::base<AutomationRemotePatternId, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemotePatternId, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemotePatternId(std::nullptr_t) noexcept {}
        AutomationRemotePatternId(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemotePatternId(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemotePoint : winrt::Microsoft::UI::UIAutomation::IAutomationRemotePoint,
        impl::base<AutomationRemotePoint, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemotePoint, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemotePoint(std::nullptr_t) noexcept {}
        AutomationRemotePoint(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemotePoint(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemotePropertyId : winrt::Microsoft::UI::UIAutomation::IAutomationRemotePropertyId,
        impl::base<AutomationRemotePropertyId, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemotePropertyId, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemotePropertyId(std::nullptr_t) noexcept {}
        AutomationRemotePropertyId(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemotePropertyId(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteRangeValuePattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteRangeValuePattern,
        impl::base<AutomationRemoteRangeValuePattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteRangeValuePattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteRangeValuePattern(std::nullptr_t) noexcept {}
        AutomationRemoteRangeValuePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteRangeValuePattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteRect : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteRect,
        impl::base<AutomationRemoteRect, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteRect, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteRect(std::nullptr_t) noexcept {}
        AutomationRemoteRect(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteRect(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteRowOrColumnMajor : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteRowOrColumnMajor,
        impl::base<AutomationRemoteRowOrColumnMajor, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteRowOrColumnMajor, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteRowOrColumnMajor(std::nullptr_t) noexcept {}
        AutomationRemoteRowOrColumnMajor(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteRowOrColumnMajor(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteSayAsInterpretAs : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSayAsInterpretAs,
        impl::base<AutomationRemoteSayAsInterpretAs, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteSayAsInterpretAs, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteSayAsInterpretAs(std::nullptr_t) noexcept {}
        AutomationRemoteSayAsInterpretAs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSayAsInterpretAs(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteScrollAmount : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteScrollAmount,
        impl::base<AutomationRemoteScrollAmount, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteScrollAmount, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteScrollAmount(std::nullptr_t) noexcept {}
        AutomationRemoteScrollAmount(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteScrollAmount(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteScrollItemPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteScrollItemPattern,
        impl::base<AutomationRemoteScrollItemPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteScrollItemPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteScrollItemPattern(std::nullptr_t) noexcept {}
        AutomationRemoteScrollItemPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteScrollItemPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteScrollPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteScrollPattern,
        impl::base<AutomationRemoteScrollPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteScrollPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteScrollPattern(std::nullptr_t) noexcept {}
        AutomationRemoteScrollPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteScrollPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteSelectionItemPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSelectionItemPattern,
        impl::base<AutomationRemoteSelectionItemPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteSelectionItemPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteSelectionItemPattern(std::nullptr_t) noexcept {}
        AutomationRemoteSelectionItemPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSelectionItemPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteSelectionPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSelectionPattern,
        impl::base<AutomationRemoteSelectionPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteSelectionPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteSelectionPattern(std::nullptr_t) noexcept {}
        AutomationRemoteSelectionPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSelectionPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteSelectionPattern2 : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSelectionPattern2,
        impl::base<AutomationRemoteSelectionPattern2, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteSelectionPattern2, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteSelectionPattern2(std::nullptr_t) noexcept {}
        AutomationRemoteSelectionPattern2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSelectionPattern2(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteSpreadsheetItemPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSpreadsheetItemPattern,
        impl::base<AutomationRemoteSpreadsheetItemPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteSpreadsheetItemPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteSpreadsheetItemPattern(std::nullptr_t) noexcept {}
        AutomationRemoteSpreadsheetItemPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSpreadsheetItemPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteSpreadsheetPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSpreadsheetPattern,
        impl::base<AutomationRemoteSpreadsheetPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteSpreadsheetPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteSpreadsheetPattern(std::nullptr_t) noexcept {}
        AutomationRemoteSpreadsheetPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSpreadsheetPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteString : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteString,
        impl::base<AutomationRemoteString, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteString, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteString(std::nullptr_t) noexcept {}
        AutomationRemoteString(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteString(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteStringMap : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteStringMap,
        impl::base<AutomationRemoteStringMap, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteStringMap, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteStringMap(std::nullptr_t) noexcept {}
        AutomationRemoteStringMap(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteStringMap(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteStyleId : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteStyleId,
        impl::base<AutomationRemoteStyleId, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteStyleId, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteStyleId(std::nullptr_t) noexcept {}
        AutomationRemoteStyleId(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteStyleId(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteStylesPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteStylesPattern,
        impl::base<AutomationRemoteStylesPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteStylesPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteStylesPattern(std::nullptr_t) noexcept {}
        AutomationRemoteStylesPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteStylesPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteSupportedTextSelection : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSupportedTextSelection,
        impl::base<AutomationRemoteSupportedTextSelection, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteSupportedTextSelection, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteSupportedTextSelection(std::nullptr_t) noexcept {}
        AutomationRemoteSupportedTextSelection(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSupportedTextSelection(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteSynchronizedInputPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSynchronizedInputPattern,
        impl::base<AutomationRemoteSynchronizedInputPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteSynchronizedInputPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteSynchronizedInputPattern(std::nullptr_t) noexcept {}
        AutomationRemoteSynchronizedInputPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSynchronizedInputPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteSynchronizedInputType : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSynchronizedInputType,
        impl::base<AutomationRemoteSynchronizedInputType, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteSynchronizedInputType, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteSynchronizedInputType(std::nullptr_t) noexcept {}
        AutomationRemoteSynchronizedInputType(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteSynchronizedInputType(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTableItemPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTableItemPattern,
        impl::base<AutomationRemoteTableItemPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTableItemPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTableItemPattern(std::nullptr_t) noexcept {}
        AutomationRemoteTableItemPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTableItemPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTablePattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTablePattern,
        impl::base<AutomationRemoteTablePattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTablePattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTablePattern(std::nullptr_t) noexcept {}
        AutomationRemoteTablePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTablePattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTextAttributeId : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextAttributeId,
        impl::base<AutomationRemoteTextAttributeId, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTextAttributeId, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTextAttributeId(std::nullptr_t) noexcept {}
        AutomationRemoteTextAttributeId(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextAttributeId(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTextChildPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextChildPattern,
        impl::base<AutomationRemoteTextChildPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTextChildPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTextChildPattern(std::nullptr_t) noexcept {}
        AutomationRemoteTextChildPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextChildPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTextDecorationLineStyle : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextDecorationLineStyle,
        impl::base<AutomationRemoteTextDecorationLineStyle, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTextDecorationLineStyle, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTextDecorationLineStyle(std::nullptr_t) noexcept {}
        AutomationRemoteTextDecorationLineStyle(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextDecorationLineStyle(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTextEditPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextEditPattern,
        impl::base<AutomationRemoteTextEditPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTextEditPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTextEditPattern(std::nullptr_t) noexcept {}
        AutomationRemoteTextEditPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextEditPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTextPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextPattern,
        impl::base<AutomationRemoteTextPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTextPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTextPattern(std::nullptr_t) noexcept {}
        AutomationRemoteTextPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTextPattern2 : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextPattern2,
        impl::base<AutomationRemoteTextPattern2, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTextPattern2, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTextPattern2(std::nullptr_t) noexcept {}
        AutomationRemoteTextPattern2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextPattern2(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTextPatternRangeEndpoint : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextPatternRangeEndpoint,
        impl::base<AutomationRemoteTextPatternRangeEndpoint, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTextPatternRangeEndpoint, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTextPatternRangeEndpoint(std::nullptr_t) noexcept {}
        AutomationRemoteTextPatternRangeEndpoint(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextPatternRangeEndpoint(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTextRange : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextRange,
        impl::base<AutomationRemoteTextRange, winrt::Microsoft::UI::UIAutomation::AutomationRemoteExtensionTarget, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTextRange, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteExtensionTarget, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTextRange(std::nullptr_t) noexcept {}
        AutomationRemoteTextRange(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextRange(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTextUnit : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextUnit,
        impl::base<AutomationRemoteTextUnit, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTextUnit, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTextUnit(std::nullptr_t) noexcept {}
        AutomationRemoteTextUnit(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTextUnit(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTogglePattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTogglePattern,
        impl::base<AutomationRemoteTogglePattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTogglePattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTogglePattern(std::nullptr_t) noexcept {}
        AutomationRemoteTogglePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTogglePattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteToggleState : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteToggleState,
        impl::base<AutomationRemoteToggleState, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteToggleState, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteToggleState(std::nullptr_t) noexcept {}
        AutomationRemoteToggleState(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteToggleState(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTransformPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTransformPattern,
        impl::base<AutomationRemoteTransformPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTransformPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTransformPattern(std::nullptr_t) noexcept {}
        AutomationRemoteTransformPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTransformPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteTransformPattern2 : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTransformPattern2,
        impl::base<AutomationRemoteTransformPattern2, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteTransformPattern2, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteTransformPattern2(std::nullptr_t) noexcept {}
        AutomationRemoteTransformPattern2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteTransformPattern2(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteUint : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteUint,
        impl::base<AutomationRemoteUint, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteUint, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteUint(std::nullptr_t) noexcept {}
        AutomationRemoteUint(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteUint(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteValuePattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteValuePattern,
        impl::base<AutomationRemoteValuePattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteValuePattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteValuePattern(std::nullptr_t) noexcept {}
        AutomationRemoteValuePattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteValuePattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteVirtualizedItemPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteVirtualizedItemPattern,
        impl::base<AutomationRemoteVirtualizedItemPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteVirtualizedItemPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteVirtualizedItemPattern(std::nullptr_t) noexcept {}
        AutomationRemoteVirtualizedItemPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteVirtualizedItemPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteWindowInteractionState : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteWindowInteractionState,
        impl::base<AutomationRemoteWindowInteractionState, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteWindowInteractionState, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteWindowInteractionState(std::nullptr_t) noexcept {}
        AutomationRemoteWindowInteractionState(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteWindowInteractionState(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteWindowPattern : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteWindowPattern,
        impl::base<AutomationRemoteWindowPattern, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteWindowPattern, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteWindowPattern(std::nullptr_t) noexcept {}
        AutomationRemoteWindowPattern(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteWindowPattern(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteWindowVisualState : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteWindowVisualState,
        impl::base<AutomationRemoteWindowVisualState, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteWindowVisualState, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteWindowVisualState(std::nullptr_t) noexcept {}
        AutomationRemoteWindowVisualState(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteWindowVisualState(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AutomationRemoteZoomUnit : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteZoomUnit,
        impl::base<AutomationRemoteZoomUnit, winrt::Microsoft::UI::UIAutomation::AutomationRemoteObject>,
        impl::require<AutomationRemoteZoomUnit, winrt::Microsoft::UI::UIAutomation::IAutomationRemoteObject>
    {
        AutomationRemoteZoomUnit(std::nullptr_t) noexcept {}
        AutomationRemoteZoomUnit(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::UIAutomation::IAutomationRemoteZoomUnit(ptr, take_ownership_from_abi) {}
    };
}
#endif
