
name: Generate microsoft-ui-uiautomation output

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  buildAndPush:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
    - name: Current dir
      run: |
        'CurrentDir: ' + (Get-Location)
    - name: Checkout source nvda-microsoft-ui-uiautomation
      uses: actions/checkout@v3
      with:
        repository: nvaccess/nvda-microsoft-ui-uiautomation
        path: source
        submodules: true
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build source
      run: |
        New-Item -ItemType "directory" "build"
        Set-Location source
        ./build.ps1 -SubmoduleDir "microsoft-ui-uiautomation" -OutDir "../build"
    - name: Checkout gen branch into separate folder
      uses: actions/checkout@v3
      with:
        repository: nvaccess/nvda-microsoft-ui-uiautomation
        path: out
        ref: main-out
    - name: Empty destination directory
      # empty the 'out' folder directory, but don't delete .git, or the top level directory.
      run: |
        Get-ChildItem gen -Exclude .git | Remove-Item
    - name: Copy files
      run: |
        ./source/copyFiles.ps1 -RepoRoot "source" -BuildDir "build" -DestDir "out"
    - name: Commit and push
      run: |
        # this is a git '--pretty=format' string
        # %h is SHA, %n is newline,
        # %s is commit message subject, %b is commit message body
        $COMMIT_FORMAT="Generated from %h%n%nCommit message:%n%s%n%b"
        Write-Output $COMMIT_FORMAT
        $prettyArg = $("--pretty=format:"+$COMMIT_FORMAT)
        Write-Output $prettyArg
        Set-Location source
        git log -1 HEAD $prettyArg > ../commitMsg.txt
        Set-Location ../out
        $status = $(git status --porcelain)
        if($status) {
          # Changes, use git status to add to log file for debugging.
          Write-Output "Changes detected, committing."
          git status --short
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -F ../commitMsg.txt
          git push
        } else {
          Write-Output "No changes"
        }